language: swift
os: osx
osx_image: xcode10.2
xcode_project: OperationPlus.xcodeproj

install:
  - gem update cocoapods

before_script:
  - pod lib lint --skip-tests --verbose

matrix:
  include:
    - env: TEST_DESTINATION="platform=macOS"
    - env: TEST_DESTINATION="platform=iOS Simulator,name=iPhone 8"
    - env: TEST_DESTINATION="platform=tvOS Simulator,name=Apple TV"
script:
  - xcodebuild test -scheme OperationPlus -destination "$TEST_DESTINATION"